# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calender.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt5.QtCore
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, pyqtSignal


class Ui_calender(PyQt5.QtCore.QObject):
    signal_1 = pyqtSignal(str)
    def setupUi(self, calender):
        calender.setObjectName("calender")
        calender.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(calender)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(calender)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)

        self.calendarWidget.clicked[QDate].connect(self.senddate)

        self.retranslateUi(calender)
        QtCore.QMetaObject.connectSlotsByName(calender)

    def retranslateUi(self, calender):
        _translate = QtCore.QCoreApplication.translate
        calender.setWindowTitle(_translate("calender", "Form"))

    def senddate(self,date):
        date_str=date.toString("yyyyMMdd")
        self.signal_1.emit(date_str)