# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f1_1_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.window = Dialog
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 30, 16))
        self.label_3.setObjectName("label_3")
        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setGeometry(QtCore.QRect(109, 219, 261, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(109, 119, 261, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(109, 169, 261, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(109, 19, 261, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(109, 69, 261, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 60, 16))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 220, 45, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(280, 260, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.getText)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "信托"))
        self.label_4.setText(_translate("Dialog", "信托简称"))
        self.label_2.setText(_translate("Dialog", "基金简称"))
        self.label.setText(_translate("Dialog", "基金产品"))
        self.label_5.setText(_translate("Dialog", "开放日"))
        self.pushButton.setText(_translate("Dialog", "录入"))

    def getText(self):
        dataset = pd.read_csv("products.csv")
        df2 = pd.DataFrame([[self.textEdit.toPlainText(),
                             self.textEdit_2.toPlainText(),
                             self.textEdit_3.toPlainText(),
                             self.textEdit_4.toPlainText(),
                             self.textEdit_5.toPlainText()]],
                           columns=['基金产品', '设定简称', '信托', '信托简称', '开放日'])
        df2.columns = dataset.columns
        df = pd.concat([dataset, df2], axis=0, ignore_index=True)
        df.to_csv("products.csv", index=0, encoding='utf_8_sig')
        self.window.close()

